server:
  port: 8770

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: usr-service
  security:
    user:
      password: 213100
      name: Yama
  datasource:
    url: jdbc:mysql://122.51.19.164:3306/paper_app?serverTimezone=GMT
    username: root
    password: Comfortalway1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 1
        min-idle: 0
    timeout: 50
    password: